### ISSUE TITLE
027. Symmetric Tree

### ISSUE THREAD

**Issue by ender233** [pezy/LeetCode#12]
再提个解法:  中序遍历对于每一层级把数据都存到一个`vector`中去, 如果元素为`null`就-1站位, 最终结果就是每个深度从左到右都放到了`vector`中, 这个就是判断一个`int`数组是否从中间开始对称了.  没递归优美

这个issues主要是看你描述, 用堆栈来做, 我还没遇到过堆栈解过题,  你方便检索你的记录么, 哪个题目用到了堆栈来搞树的, 我来学习一下.

**Comment by pezy** [comment]
这个解法很直观，但效率的确较低，占了空间复杂度，也没放过时间复杂度。

至于堆栈，[这道题](https://github.com/pezy/LeetCode/blob/master/027.%20Symmetric%20Tree/solution.h) 我就是用堆栈来解的嘛。开始的递归解法我后来给删掉了。

**Comment by ender233** [comment]
哦, 原来我看到的链接是历史你删掉的代码. github基本不会用

堆栈思路很精妙啊, 我只能想出来递归.  
面试的时候想出来递归, 面试官可能会说能不能再像个迭代呢. 
如果想出来我那种, 估计面试官会说: 我们后面有消息会通知你, 下一位.
