### ISSUE TITLE
question_064. Valid Sudoku

### ISSUE THREAD

**Issue by ender233** [pezy/LeetCode#14]
这个题, 我看标签给的是`hash_table` 
然后我用的是`std::map<int, set<int>>`来处理的, 那实际上和hash_table没什么关系吧. 
即使是`unordered_map` `unordered_set`  也是stl内部的数据结构. 不知这题哪里考察`hash_table`了

**Comment by pezy** [comment]
Hash table 在 C++ 里，对应的是：[unordered_map](http://en.wikipedia.org/wiki/Hash_table#Implementations)。考察的是 Hash table 的用法，如果选择了 C++ 语言，那么自然就是考察 unordered_map 的用法。

使用 `std::map` 也可以解决问题，但那本质是红黑树，在时间复杂度上会多付出些代价。
