### ISSUE TITLE
064. Valid Sudoku

### ISSUE THREAD

**Issue by ender233** [pezy/LeetCode#15]
提供个不太实用，但是万一面试官问起来可以扯一扯的方法，算法归为迭代

其实是模拟人在做数独：`找到出现频率最多的数字（比如说数字3），遍历没有出现这个数字的小的九宫格，然后对已经存在的数字3分别横向纵向发射，目标九宫格还剩下一个空格没扫射到，那么就填数字3了`

以题目为例：
+-----------------+
|5 3              |
|6 |   1 9 5      |
|  9 8         6  |
|8 |-----6-------3|
|4 +---8---3     1|
|7 | *   2       6|
|  6         2 8  |
|      4 1 9     5|
|        8     7 9|
+-----------------+

找到数字3， 小九宫格序号分别为 0 1 2 3 4 5 6 7 8， 看3号小九宫格，小九宫格内前两行和第二列都被其他的数字3的横向纵向扫射到了，最后只有`*`这个位置填3了。 

实际算法可以采用从数字1遍历到数字9对非存在数字的九宫格扫描，如果还有剩余，那么继续遍历，这个迭代的方式基本上是问题规模逐步减小的，扫描几次后，效率基本上瞬间定位。

所以时间复杂度应该比较小， 具体到实现 1到9的位置可以初始就存入map中， 小九宫格确定剩余空闲位是否为1时候应该比较繁琐。 

--------

**Comment by pezy** [comment]
@ender233  谢谢提供思路。

时间复杂度，在这道题里，主要体现在对整个 board 扫描了几次。我并未完全理解你的算法，可能用伪码的方式描述，要更加清晰明确一些。

**Comment by ender233** [comment]
单纯用这个算法还搞不定数独,  我之前试的是简单的,  现在用了这个方法搞中级的就不行了, 还是得借助别方式.  至于我说的这个算法,  以后有空手机或者pad下个数独游戏, 点击某数字, 这个数字全局都会高亮, 就是提示用户用这个算法来做人工扫描.
