### ISSUE TITLE
068. Jump Game

### ISSUE THREAD

**Issue by ender233** [pezy/LeetCode#16]
这个题目给的`tag`是 `array` `greedy` , 你这个算法可以归做`greedy`么?

你这个解法真强大..  我开始就想偏了, 递归-超时 动态规划-超时.  
看了你的解法, 我还是想了好几遍才想明白,  厉害!  你这手机三行就ac了

**Comment by pezy** [comment]
你说得对，这就是贪心法。（现在一想还挺清楚了）

首先每一次都做出最优选择（取 max），其次不保存历史结果（与 DP 最大区别）。典型的贪心思想。

至于手机三行 AC，没记错的话，那天应该是去天津玩，边玩脑子里一直想，突然想通了，就掏出手机试着提交，也真没想到 AC 了。当时也蛮兴奋的。（所以我属于需要想很久才下笔的那种）
