### ISSUE TITLE
006. Unique Binary Search Trees

### ISSUE THREAD

**Issue by ender233** [pezy/LeetCode#5]
这个不一定非要知道卡特兰数才可以搞定.  root节点确认,左右两边的数集就确定了.

递归的方式最好理解, 不过会有超时,我也是n=19就挂掉了
用一个全局数组或者map标识一下已经计算过的结果,可以解决这个.
比如这样:

`for(int i=1; i<=n; i++)
	{
		mpNum[n] += numTrees(i-1)*numTrees(n-i);
	}`

循环也可以解决,但是看了别人的代码 总是理解不上去.

以前注册过github就没咋会用, 没找到评论功能, issue是提bug的吧.
可以关闭此条了 我就想评论一下.

**Comment by pezy** [comment]
@ender233 感谢评论，issue 不仅仅是提 bug 的地方，也供讨论。

你的这个方法应该是 DP 的思路。（我的 DP 到现在都不是很好，所以每一次解题，都是最后才考虑。。）

不过我的确也没想到这道题可以这样解。（虽然有空间复杂度，但很值得。）

整理下你的解法：

```cpp
int numTree(int n)
{
    vector<int> cache(n+1);
    cache[0] = cache[1] = 1;
    
    for (int i=2; i<=n; ++i)
        for (int j=1; j<=i; ++j)
            cache[i] += cache[j-1] * cache[i-j];
    
    return cache[n];
}
```

最后，真的感谢你参与讨论~

**Comment by ender233** [comment]
@pezy  好的, 不介意就可以.  我最近也在做leetCode

不过做的慢, 1小时内,一天不能保证刷一个.   issue不错, 有问题这里和你请教.
------
又看了遍你这个实现,  理解了循环DP.  thx.
