### ISSUE TITLE
021. Convert Sorted Array to Binary Search Tree

### ISSUE THREAD

**Issue by ender233** [pezy/LeetCode#6]
想了好久, 做出来了, 回头看你这实现  才5行, 看来刷这个优先想递归.

我就没想可以直接递归.

非递算法是按照这个图示解出的:循环num,所有插入的新节点都是root->right一直right,
然后上去找某个节点的左树left深度小于right的化,那么就可以调整位置了.

http://www.cs.usfca.edu/~galles/visualization/AVLtree.html

**Comment by pezy** [comment]
AVL 树算是比较高级的数据结构了，本质是一个平衡二叉树，故重点就在**调整位置**。如果你能很熟练的运用这个数据结构，我想同类的都没问题，如 BST, 红黑树等等。

但对于我来说，面试里，较为紧张的情况下，很难有把握写清楚这些树的算法，所以递归一定是首选。思路清晰、代码简单，就算和面试官讨论也不会出岔子。。。 :smiley:

**Comment by ender233** [comment]
nice.
