### ISSUE TITLE
031. Generate Parentheses

### ISSUE THREAD

**Issue by ender233** [pezy/LeetCode#7]
说明里`if (n>0) addParenthesis(str+"(", n-1, m+1);`

`m+1` 应该 `m` ? 一次左括号右括号只放置一个.

----

看你代码,原来是实现方式不一样, 我入参都是(n, n)了.

**Comment by pezy** [comment]
@ender233 `n` 为所需左括号的个数，`m` 为所需右括号的个数。

当增加一个 "(" 的时候，左括号的需求少了一个 (n-1), 右括号的需求多了一个 (m+1)，因为有左必有右。

注意结合初始值：`addParenthesis("", n, 0);`，左括号需求为 `n`, 右括号需求为 `0`(因为此刻一个左括号都没有放).

**Comment by ender233** [comment]
@pezy   刚才回头过来看代码的时候  发现判断逻辑不太一样.
我入参都是`("", n, n)`  一个递增一个递减, 麻烦的一处在于判断m的时候要保证比`n`大
```
if(n>0) addString(str+"(", n-1, m);
if(m>0 && n<m) addString(str+")", n, m-1);
```
如果没有`n<m`的判断, 会出现这种`))`以至于最后还需要堆栈来判断是否匹配.

你的实现好太多了, 每次对照代码我代码都是又臭又长. 这道题是想了好一会儿没啥思路看了你的说明..
多谢啊.

**Comment by pezy** [comment]
@ender233 没关系，做的时候尽量精简代码，以免笔试面试真遇到的时候，犯糊涂。。。 :ghost:
